<?php
/**
* Author: Tomas Pavlatka [tomas.pavlatka@gmail.com]
* Date: 10.8.2010
**/ 

?>

<h1><?php echo $this->h1. ' &#187; '.$this->h2; ?></h1>

<?php 
// Buttons.
$buttons = array(
    'links' => array(
        array('text'=>$this->trans('List'),'link'=>PTX_Anchor::get('widget','list','admin'),'class'=>'btn'),
    ),
);
echo $this->partial('_elements/buttons.phtml',array('options'=>$buttons));

// Messages.
if(isset($this->msgs)) {
    echo $this->viewMsgs($this->msgs);
}

// Content buttons.
$buttons = array(
    'header' => $this->escape($this->data['name_'.$this->locale]), 
    'buttons' => $this->widgetOptions,
);
echo $this->partial('_elements/content-buttons.phtml',array('options'=>$buttons));
