<?php
/**
* Author: Tomas Pavlatka [tomas.pavlatka@gmail.com]
* Date: 10.8.2010
**/
?>
<h1><?php echo $this->h1. ' &#187; ' .$this->h2; ?></h1>

<?php 
// Buttons.
$buttons = array(
    'links' => array(
        array('text'=>$this->trans('List'),'link'=>PTX_Anchor::get('widget','list','admin'),'class'=>'btn'),
        array('text'=>$this->trans('Reset form'),'link'=>'/admin/widget/edit/id/'.(int)$this->data['id'],'class'=>'btn'),
    ),
);
echo $this->partial('_elements/buttons.phtml',array('options'=>$buttons));
?>

<h2><?php echo $this->widgetTypeName($this->data['parent_type']).': '.$this->data['name_'.$this->locale]; ?></h2>

<?php 
// Text widget - load WYSIWYG editors.
if($this->data['parent_type'] == 'text') {
    $languages = Admin_Model_DbSelect_Languages::getActive();
    $options = array('ids' => array());
    foreach($languages as $key => $values) {
        $options['ids'][] = 'wcontent'.$values['code'];
    }
    echo $this->partial('_elements/wysiwyg-setting.phtml',array('options'=>$options));
}

// Messages.
if(isset($this->msgs)) {
    echo $this->viewMsgs($this->msgs);
}

// Form.
echo $this->form;
