<h1><?php echo $this->h1. ' &#187; '.$this->h2; ?></h1>
<?php
// Buttons.
$buttons = array(
    'links' => array(
        array('text'=>$this->trans('New User'),'link'=>"/admin/user/add",'class'=>'btn')
    ),
);
echo $this->partial('_elements/buttons.phtml',array('options'=>$buttons));


// Messages.
if(isset($this->msgs)) {
	echo $this->viewMsgs($this->msgs);
} 

// Paginator.
echo $this->paginationControl($this->paginator,'Sliding','_paginator/default.phtml'); 

// Restrict form.
$formOptions = array(
    'action' => '/admin/user/transform',
    'method' => 'post',
    'class' => 'ptxinrowform',

    'fields' => array(
        'sort' => array('name' => 'sort', 'id' => 'sort', 'class'=>'input-text', 'values' => $this->sortPossibilities,'type' => 'select','empty_value' => $this->trans('- sort by -')),
        'role' => array('name' => 'role', 'id' => 'role', 'class'=>'input-text', 'values' => $this->userRoles,'type' => 'select','empty_value' => $this->trans('- all roles -')),
        'input' => array(),
        'search' => array()),
    'params' => $this->params,
); 
echo $this->partial('_elements/restrict-form.phtml',array('options'=>$formOptions));

// Table.
$tableOptions = array(
    'columns' => array(
        array('name' => $this->trans('role'),'column'=>'role'),
        array('name' => $this->trans('person name'),'column'=>'name'),
        array('name' => $this->trans('email'),'column'=>'email'),
        ),
    
    'actions' => array('status','detail','edit','password','delete'),
    'controller' => 'user',
    'status_action' => 'user-status',              
    'records' => $this->paginator->getCurrentItems(),
);
echo $this->partial('_elements/table.phtml',array('options'=>$tableOptions));

// Paginator.
echo $this->paginationControl($this->paginator,'Sliding','_paginator/default.phtml'); ?>



