<?php
/**
* Author: Tomas Pavlatka [tomas.pavlatka@gmail.com]
* Date: 22.8.2010
**/
?>

<h1><?php echo $this->h1. ' &#187; '.$this->h2; ?></h1>

<?php
// Buttons.
$buttons = array(
    'links' => array(
        array('text'=>$this->trans('New Static page'),'link'=>"/admin/static-page/add",'class'=>'btn')
    ),
);
echo $this->partial('_elements/buttons.phtml',array('options'=>$buttons));

// Messages.
if(isset($this->msgs)) {
    echo $this->viewMsgs($this->msgs);
} 

// Paginator.
echo $this->paginationControl($this->paginator,'Sliding','_paginator/default.phtml');

// Restrict form.
$formOptions = array(
    'action' => '/admin/static-page/transform',
    'method' => 'post',
    'class' => 'ptxinrowform',

    'fields' => array(
        'sort' => array('name' => 'sort', 'id' => 'sort', 'class'=>'input-text', 'values' => $this->sortPossibilities,'type' => 'select','empty_value' => $this->trans('- sort by -')),
        'input' => array(),
        'search' => array()),
    'params' => $this->params,
); 
echo $this->partial('_elements/restrict-form.phtml',array('options'=>$formOptions));

// Table.
$tableOptions = array(
    'columns' => array(
        array('name' => $this->trans('name'),'column'=>'name'),
        array('name' => $this->trans('shown'),'column'=>'shown','width'=>"100",'class'=>'t-center'),
        array('name' => $this->trans('published'),'column'=>'published','width'=>"120",'class'=>'t-center','helper'=>'viewDate'),
        ),
    
    'actions' => array('status','edit','delete'),
    'controller' => 'static-page',
    'status_action' => 'static-page-status',              
    'records' => $this->paginator->getCurrentItems(),
);
echo $this->partial('_elements/table.phtml',array('options'=>$tableOptions));

// Paginator. 
echo $this->paginationControl($this->paginator,'Sliding','_paginator/default.phtml'); 