<?php
/**
 * Author: Tomas Pavlatka [tomas@pavlatka.cz]
 * Created: Oct 18, 2011
 */
 
$params = array(
    'block_before'  => '<ul class="tabbed">',
    'block_after'   => '</ul>',
    'item_before'   => '<li>',
    'item_after'    => '</li>',
    'item_selected_before' => '<li class="current_page_item">',
    'item_selected_after'  => '</li>',
    'parent_id'     => 0);
echo $this->getMenu4Print(1,$params);