<?php
/**
 * Author: Tomas Pavlatka
 * Email: tomas.pavlatka@gmail.com
 * Created: 23.1.2010 20:17:27
 */
?>

<h1><?php echo $this->h1. ' &#187; ' .$this->h2; ?></h1>

<?php  
// Buttons.
$buttons = array(
    'links' => array(
        array('text'=>$this->trans('List'),'link'=>PTX_Anchor::get('banner','list','admin'),'class'=>'btn'),
        array('text'=>$this->trans('Logo'),'link'=>"/admin/banner/logo/id/".(int)$this->data['id'],'class'=>'btn'),
        array('text'=>$this->trans('Reset form'),'link'=>"/admin/banner/edit/id/".(int)$this->data['id'],'class'=>'btn'),
    ),
);
echo $this->partial('_elements/buttons.phtml',array('options'=>$buttons));
?>

<h2><?php echo $this->escape($this->data['name_'.$this->locale]); ?></h2>

<?php
// Messages.
if(isset($this->msgs)) {
    echo $this->viewMsgs($this->msgs);
}
?>
<p class="msg info"><?php echo $this->trans('To update image of banner, press <b>Image button</b> above.',false); ?></p>
<?php 
// Form.
echo $this->form;
