<?php
/**
* Author: Tomas Pavlatka [tomas.pavlatka@gmail.com]
* Date: 10.8.2010
**/


?>
<h1><?php echo $this->h1. ' &#187; ' .$this->h2; ?></h1>

<?php
// Buttons.
$buttons = array(
    'links' => array(
        array('text'=>$this->trans('List'),'link'=>PTX_Anchor::get('article','list','admin'),'class'=>'btn'),
        array('text'=>$this->trans('Reset form'),'link'=>'/admin/article/add','class'=>'btn'),
    ),
);
echo $this->partial('_elements/buttons.phtml',array('options'=>$buttons));

$languages = Admin_Model_DbSelect_Languages::getActive();
// Load WYSIWYG editors.
$options = array(
    'ids' => array(),
);
foreach($languages as $langKey => $langValues) {
    $options['ids'][] = 'pcontent'.$langValues['code'];
    $options['ids'][] = 'perex'.$langValues['code'];
}
echo $this->partial('_elements/wysiwyg-setting.phtml',array('options'=>$options));

// Messages.
if(isset($this->msgs)) {
    echo $this->viewMsgs($this->msgs);
}

// Form.
echo $this->form;