<?php 
$projectConfig = PTX_Session::getSessionValue('settings', 'project');
$locale = Zend_Registry::get('PTX_Locale');
?>
<div id="tray" class="box">
    <p class="f-left box">
        <span class="f-left" id="switcher">
            <a href="#" rel="1col" class="styleswitch ico-col1" title=""><img src="<?php echo $this->baseUrl(); ?>/project/admin/css/design/switcher-1col.gif" alt="" /></a>
        </span>
        <?php 
        echo $this->trans('PROJECT').': ';
        if(isset($projectConfig['name'.$locale])) {
            echo '<a href="#">'.$projectConfig['name'.$locale].'</a>'; 
        }
        ?>
    </p>
</div> <!--  /tray -->