<?php
/**
 * Author: Tomas Pavlatka [tomas.pavlatka@gmail.com]
 * Created: Sep 21, 2011
 */
  
$params = array(
    'header_before' => '<div class="box-title">',
    'header_after'  => '</div>',
    'block_before'  => '<div class="box">',
    'block_after'   => '</div>',
    'item_before'   => '<div class="box-content">',
    'item_after'    => '</div>',
);

if(isset($this->params)) {
    $params = array_merge($params,$this->params);
}
echo $this->getWidget4Print(5,$params);