<?php
/**
* Author: Tomas Pavlatka [tomas.pavlatka@gmail.com]
* Date: 10.8.2010
**/

?>

<h1><?php echo $this->h1. ' &#187; ' .$this->h2; ?></h1>

<?php
// Buttons.
$buttons = array(
    'links' => array(
        array('text'=>$this->trans('List'),'link'=>PTX_Anchor::get('menu-input','list','admin'),'class'=>'btn'),
        array('text'=>$this->trans('Reset form'),'link'=>'/admin/menu-input/edit/id/'.(int)$this->data['id'],'class'=>'btn'),
    ),
);
echo $this->partial('_elements/buttons.phtml',array('options'=>$buttons));
?>

<h2><?php echo $this->menuTypeName($this->type,$this->parent); ?></h2>

<?php 
// Messages.
if(isset($this->msgs)) {
    echo $this->viewMsgs($this->msgs);
}

// Form.
echo $this->form;