<?php
/**
 * Author: Tomas Pavlatka [tomas@pavlatka.cz]
 * Created: Oct 19, 2011
 */
 

$params = array(
    'block_before'  => '<div class="left">',
    'block_after'   => '</div>',
    'item_before'   => '',
    'item_after'    => ' <span class="text-separator">|</span> ',
    'item_selected_before'   => '',
    'item_selected_after'    => ' <span class="text-separator">|</span> ',
    'parent_id'     => 0);
echo $this->getMenu4Print(3,$params);