<?php
// Variables.
$projectConfig = PTX_Session::getSessionValue('settings', 'project');
$config = Zend_Registry::get('config');
$locale = Zend_Registry::get('PTX_Locale');
?>
<div id="main-02">
    <div id="login-top"></div>
    <div id="login-box">
    
        <!-- Logo -->
        <p class="nom t-center"><img src="<?php echo $config->ptx->project->logo->file; ?>" width="<?php echo (int)$config->ptx->project->logo->width; ?>" height="<?php echo (int)$config->ptx->project->logo->height; ?>" alt="<?php echo $projectConfig['name'.$locale]; ?>" title="<?php echo $projectConfig['name'.$locale]; ?>" /></p>
        
        <!-- Message. -->
        <p class="msg info"><?php echo $this->trans('Enter your <b>e-mail address</b> and <b>password</b>.',false); ?></p>        
        <?php
        if(is_array($this->msgs)) {
            echo $this->viewMsgs($this->msgs);
        } 

        echo $this->form; ?>
        <ul><li><a href="/authentication/forgot"><?php echo $this->trans('Forgot login data'); ?> &#187;</a></ul>
    </div> <!-- /login-box -->
    <div id="login-bottom"></div>
</div> <!-- /main -->